CREATE TABLE public.client_onboarding (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  nome_imobiliaria TEXT NOT NULL,
  nome_responsavel TEXT NOT NULL,
  telefone_responsavel TEXT NOT NULL,
  email_principal TEXT NOT NULL,
  whatsapp_leads TEXT NOT NULL,
  cidades_atuacao TEXT[] DEFAULT '{}',
  instagram TEXT,
  facebook TEXT,
  site TEXT,
  qtd_corretores INTEGER DEFAULT 0,
  tipo_atuacao TEXT,
  objetivo_principal TEXT,
  tipos_imoveis TEXT[] DEFAULT '{}',
  regioes_prioritarias TEXT,
  possui_banco_criativos BOOLEAN DEFAULT false,
  link_drive_criativos TEXT,
  link_identidade_visual TEXT,
  possui_sdr BOOLEAN DEFAULT false,
  horario_atendimento TEXT,
  crm_utilizado TEXT,
  login_crm TEXT,
  senha_crm TEXT,
  email_integracoes TEXT,
  possui_automacoes BOOLEAN DEFAULT false,
  etapas_funil TEXT,
  automacoes_desejadas TEXT[] DEFAULT '{}',
  link_drive_criativos_acesso TEXT,
  link_drive_administrativo TEXT,
  pasta_fotos_videos TEXT,
  horario_reuniao_semanal TEXT,
  horario_relatorios TEXT,
  emails_adicionais_relatorios TEXT,
  observacoes TEXT,
  cliente_id UUID REFERENCES public.clientes(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'pendente',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
)